# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BannerAdvancedExamples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BannerAdvancedExamples
  pod 'FluctSDK'

  target 'BannerAdvancedExamplesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BannerAdvancedExamplesUITests' do
    # Pods for testing
  end

end
